### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by dmitry-zaitsev** [sulewicz/springlayout#5]
Thanks for your library! It is very promising, although lack of Maven support makes it problematic to use in production environment.

Could you please migrate project to Maven (or Gradle) and, in best case, deploy to Maven central repository?

**Comment by sulewicz** [comment]
Hi Dmitry!

I planned to do that in a near future, but since now I have a request from you I will need to put higher priority on that :).
I'll try to do that in a week or two.
Thanks for your feedback!

Cheers,
Szymon

**Comment by sulewicz** [comment]
Hi Dmitry!

I have migrated project to gradle, added pom.xml to "library" and also deployed the project to Maven central (actually it will take some time until it lands in the Maven Central repository, but it is already available in some other repositories used by gradle, for example in repo.jfrog.org).

**Comment by dmitry-zaitsev** [comment]
Thanks!
So, time has come to get rid of bunch of nested layouts  :+1:
